### ISSUE TITLE
PR's from original

### ISSUE THREAD

**Issue by yunusga** [solversgroup/wp-multilang#1]
Forked from: [VaLeXaR/wp-multilang](https://github.com/VaLeXaR/wp-multilang)

- [x] #114 Woo: Support for registration/checkout policy fields
- [x] #113 Fix remove necessary slashes from languages that are not currently edited (Carbon Fields rich text)
- [x] #112 Yoast SEO: Fix config options
- [x] #111 Woo: Fix empty attribute values on frontend
- [x] #110 Woo: Add woocommerce_format_content filter to translate
- [x] #96 Optimize wpm_string_to_ml_array and other functions.

**Comment by yunusga** [comment]
Closed, all PR merged in new release [VaLeXaR/wp-multilang](https://github.com/VaLeXaR/wp-multilang)
